server:
  port: 8085
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
     url: jdbc:mysql://localhost:3307/loansdb
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"