version: '3.8'

services:

  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - "3305:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    networks:
      - QBank

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - QBank

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - "3304:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    networks:
      - QBank

  configserver:
    image: "vermau2k01053/config-server:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8071/actuator/health/readiness"]
      interval: 10s
      start_period: 10s
      retries: 10
    networks:
      - QBank

  accounts:
    image: "vermau2k01053/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    networks:
      - QBank
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb  # Use internal port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "vermau2k01053/loans:s7"
    container_name: loans-ms
    ports:
      - "8085:8085"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    networks:
      - QBank
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb  # Use internal port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: default

  cards:
    image: "vermau2k01053/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    networks:
      - QBank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb  # Use internal port
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: default

networks:
  QBank:
    driver: "bridge"
